version: '3'
services:
  web:
    build: .
    env_file:
      - ./environments/db.env
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  public-data:
  tmp-data:
  log-data:
  db-volume: