version: '3'
services:
  web:
    build: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -e production -C config/puma.rb
    environment:
      RAILS_ENV: 'production'
      RACK_ENV: 'production'
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-volume:/var/lib/mysql
  nginx:
    build:
      context: nginx
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  public-data:
  tmp-data:
  log-data:
  db-volume: